# Generated by Django 5.2.13 on 2026-05-19 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organizacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimonioCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo_mcasp', models.CharField(blank=True, default='', max_length=30)),
                ('nome_conta_pcasp', models.CharField(blank=True, default='', max_length=200)),
                ('vida_util_anos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('taxa_depreciacao_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_residual_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('metodo_depreciacao', models.CharField(choices=[('linear', 'Linear'), ('saldos_decrescentes', 'Saldos Decrescentes'), ('unidades_produzidas', 'Unidades Produzidas')], default='linear', max_length=30)),
                ('deprecia', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Categoria de Patrimônio',
                'verbose_name_plural': 'Categorias de Patrimônio',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patrimonio', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, default='', max_length=100)),
                ('modelo', models.CharField(blank=True, default='', max_length=100)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=100)),
                ('cor', models.CharField(blank=True, default='', max_length=50)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('valor_aquisicao', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('data_inicio_depreciacao', models.DateField(blank=True, null=True)),
                ('valor_depreciado_acumulado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_liquido_contabil', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('nota_fiscal_numero', models.CharField(blank=True, default='', max_length=50)),
                ('estado_conservacao', models.CharField(choices=[('novo', 'Novo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim'), ('inservivel', 'Inservível')], default='bom', max_length=12)),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('em_manutencao', 'Em Manutenção'), ('baixado', 'Baixado'), ('transferido', 'Transferido'), ('emprestado', 'Emprestado')], default='ativo', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios_criados', to=settings.AUTH_USER_MODEL)),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios', to='organizacoes.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios', to='organizacoes.setor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrimonios', to='patrimonio.patrimoniocategoria')),
            ],
            options={
                'verbose_name': 'Patrimônio',
                'verbose_name_plural': 'Patrimônios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatrimonioDepreciacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField()),
                ('valor_depreciado_mes', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_acumulado_apos', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_liquido_apos', models.DecimalField(decimal_places=2, max_digits=14)),
                ('metodo_aplicado', models.CharField(max_length=30)),
                ('processado_em', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciacoes', to='patrimonio.patrimonio')),
            ],
            options={
                'verbose_name': 'Depreciação de Patrimônio',
                'verbose_name_plural': 'Depreciações de Patrimônio',
                'ordering': ['-mes_referencia'],
            },
        ),
        migrations.CreateModel(
            name='PatrimonioFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caminho_arquivo', models.CharField(max_length=500)),
                ('caminho_thumb', models.CharField(blank=True, default='', max_length=500)),
                ('url_full', models.CharField(blank=True, default='', max_length=800)),
                ('url_thumb', models.CharField(blank=True, default='', max_length=800)),
                ('largura', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('altura', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tamanho_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('mime', models.CharField(default='image/jpeg', max_length=50)),
                ('hash', models.CharField(blank=True, default='', max_length=64)),
                ('principal', models.BooleanField(default=False)),
                ('disk', models.CharField(default='public', max_length=30)),
                ('legenda', models.CharField(blank=True, default='', max_length=255)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonio_fotos_enviadas', to=settings.AUTH_USER_MODEL)),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='patrimonio.patrimonio')),
            ],
            options={
                'verbose_name': 'Foto de Patrimônio',
                'verbose_name_plural': 'Fotos de Patrimônio',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PatrimonioLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('predio', 'Prédio'), ('andar', 'Andar'), ('sala', 'Sala'), ('outro', 'Outro')], default='sala', max_length=8)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='patrimonio.patrimoniolocal')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonio_locais', to='organizacoes.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonio_locais', to='organizacoes.setor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Local Patrimonial',
                'verbose_name_plural': 'Locais Patrimoniais',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonios', to='patrimonio.patrimoniolocal'),
        ),
        migrations.CreateModel(
            name='PatrimonioQrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inutilizado', 'Inutilizado')], default='ativo', max_length=12)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('impresso_em', models.DateTimeField(blank=True, null=True)),
                ('qtd_impressoes', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonio_qrcodes_gerados', to=settings.AUTH_USER_MODEL)),
                ('patrimonio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcode', to='patrimonio.patrimonio')),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonio_qrcodes', to='organizacoes.secretaria')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'QR Code de Patrimônio',
                'verbose_name_plural': 'QR Codes de Patrimônio',
            },
        ),
        migrations.CreateModel(
            name='PatrimonioCadastroIa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_hash', models.CharField(db_index=True, max_length=64)),
                ('modelo_usado', models.CharField(max_length=60)),
                ('resposta_bruta', models.JSONField()),
                ('multiplos_bens', models.BooleanField(default=False)),
                ('tokens_input', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tokens_output', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('custo_estimado_brl', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patrimonio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastros_ia', to='patrimonio.patrimonio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patrimonio_cadastros_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cadastro via IA',
                'verbose_name_plural': 'Cadastros via IA',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'imagem_hash'), name='uq_pat_ia_tenant_hash')],
            },
        ),
        migrations.AddIndex(
            model_name='patrimoniocategoria',
            index=models.Index(fields=['tenant', 'ativo'], name='patrimonio__tenant__94d6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimoniodepreciacao',
            index=models.Index(fields=['mes_referencia'], name='patrimonio__mes_ref_ffe782_idx'),
        ),
        migrations.AddConstraint(
            model_name='patrimoniodepreciacao',
            constraint=models.UniqueConstraint(fields=('patrimonio', 'mes_referencia'), name='uq_pat_dep_patrimonio_mes'),
        ),
        migrations.AddIndex(
            model_name='patrimoniofoto',
            index=models.Index(fields=['patrimonio', 'ordem'], name='patrimonio__patrimo_c1ed97_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimoniofoto',
            index=models.Index(fields=['patrimonio', 'principal'], name='pat_fotos_capa_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimoniolocal',
            index=models.Index(fields=['secretaria', 'setor'], name='patrimonio__secreta_ecbdb7_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimoniolocal',
            index=models.Index(fields=['tenant', 'parent'], name='patrimonio__tenant__7e3033_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimonio',
            index=models.Index(fields=['situacao'], name='patrimonio__situaca_cbc14a_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimonio',
            index=models.Index(fields=['categoria'], name='patrimonio__categor_394619_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimonio',
            index=models.Index(fields=['local'], name='patrimonio__local_i_bc6796_idx'),
        ),
        migrations.AddIndex(
            model_name='patrimonio',
            index=models.Index(fields=['tenant', 'secretaria'], name='patrimonio__tenant__bb10d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='patrimonio',
            constraint=models.UniqueConstraint(fields=('tenant', 'numero_patrimonio'), name='uq_patrimonio_tenant_numero'),
        ),
    ]
