# Generated by Django 5.2.13 on 2026-05-14 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
        ('core', '0001_initial'),
        ('organizacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('image_key', models.CharField(help_text='R2 object key (pra delete futuro).', max_length=500)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_count', models.PositiveIntegerField(default=0, help_text='Quantos agentes receberam o comando.')),
                ('secretaria', models.ForeignKey(blank=True, help_text='Escopo opcional — se vazio, aplica em todo o tenant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallpapers', to='organizacoes.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallpapers', to='organizacoes.setor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallpapers_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Papel de parede',
                'verbose_name_plural': 'Papeis de parede',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='configuraco_tenant__997ce7_idx')],
            },
        ),
    ]
