# Generated by Django 5.2.13 on 2026-05-19 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('frota', '0001_initial'),
        ('organizacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CidadeDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('uf', models.CharField(max_length=2)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Cidade-Destino',
                'verbose_name_plural': 'Cidades-Destino',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HorarioTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('descricao', models.CharField(blank=True, default='', max_length=60)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Horário Sugerido',
                'verbose_name_plural': 'Horários Sugeridos',
                'ordering': ['ordem', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='LocalAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cidade_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locais_atendimento', to='transporte.cidadedestino')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Local de Atendimento',
                'verbose_name_plural': 'Locais de Atendimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='LocalEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Local de Embarque',
                'verbose_name_plural': 'Locais de Embarque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('cpf', models.CharField(blank=True, default='', max_length=14)),
                ('cnh', models.CharField(max_length=20)),
                ('cnh_categoria', models.CharField(max_length=5)),
                ('cnh_validade', models.DateField()),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('observacao', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('access_token', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motorista_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('cpf', models.CharField(blank=True, default='', max_length=14)),
                ('cns', models.CharField(blank=True, default='', max_length=15)),
                ('cds_individual', models.CharField(blank=True, default='', max_length=80)),
                ('telefone', models.CharField(blank=True, default='', max_length=30)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, default='', max_length=1)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('bairro', models.CharField(blank=True, default='', max_length=120)),
                ('observacao', models.TextField(blank=True, default='')),
                ('unidade', models.CharField(blank=True, default='', max_length=160)),
                ('equipe', models.CharField(blank=True, default='', max_length=120)),
                ('microarea', models.CharField(blank=True, default='', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='organizacoes.secretaria')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ViagemTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_saida', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('sim_saude', 'SIM Saúde'), ('outro', 'Outro')], default='sim_saude', max_length=20)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cidade_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='transporte.cidadedestino')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens_transporte_criadas', to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens', to='transporte.horariotransporte')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens_transporte', to='transporte.motorista')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens_transporte', to='frota.veiculo')),
            ],
            options={
                'verbose_name': 'Viagem de Transporte',
                'verbose_name_plural': 'Viagens de Transporte',
                'ordering': ['-data', '-hora_saida'],
            },
        ),
        migrations.CreateModel(
            name='ProtocoloExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('exame', 'Exame'), ('laudo', 'Laudo'), ('receita', 'Receita'), ('atestado', 'Atestado'), ('outros', 'Outros')], default='exame', max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('numero_protocolo', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('aguardando_retirada', 'Aguardando Retirada'), ('aguardando_entrega', 'Aguardando Entrega'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='aguardando_retirada', max_length=30)),
                ('previsao_retirada', models.DateField(blank=True, null=True)),
                ('retirado_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_em', models.DateTimeField(blank=True, null=True)),
                ('entregue_para', models.CharField(blank=True, default='', max_length=160)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_criados', to=settings.AUTH_USER_MODEL)),
                ('entregue_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_entregues', to=settings.AUTH_USER_MODEL)),
                ('local_atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_exame', to='transporte.localatendimento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocolos_exame', to='transporte.paciente')),
                ('retirado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_retirados', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
                ('viagem_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_origem', to='transporte.viagemtransporte')),
                ('viagem_retirada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_retirada', to='transporte.viagemtransporte')),
            ],
            options={
                'verbose_name': 'Protocolo de Exame',
                'verbose_name_plural': 'Protocolos de Exame',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassageiroViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalidade', models.CharField(max_length=200)),
                ('presente', models.BooleanField(blank=True, null=True)),
                ('embarcou_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acompanhante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acompanhante_viagens', to='transporte.paciente')),
                ('check_in_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passageiros_check_in', to=settings.AUTH_USER_MODEL)),
                ('local_atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passageiros_viagem', to='transporte.localatendimento')),
                ('local_embarque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passageiros_viagem', to='transporte.localembarque')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passageiro_viagens', to='transporte.paciente')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passageiros', to='transporte.viagemtransporte')),
            ],
            options={
                'verbose_name': 'Passageiro de Viagem',
                'verbose_name_plural': 'Passageiros de Viagem',
                'ordering': ['viagem_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='cidadedestino',
            index=models.Index(fields=['tenant', 'ativo'], name='transporte__tenant__b72557_idx'),
        ),
        migrations.AddConstraint(
            model_name='cidadedestino',
            constraint=models.UniqueConstraint(fields=('tenant', 'nome', 'uf'), name='uq_cidade_dest_tenant_nome_uf'),
        ),
        migrations.AddIndex(
            model_name='horariotransporte',
            index=models.Index(fields=['tenant', 'ativo', 'ordem'], name='transporte__tenant__dbcbea_idx'),
        ),
        migrations.AddConstraint(
            model_name='horariotransporte',
            constraint=models.UniqueConstraint(fields=('tenant', 'hora'), name='uq_horario_tenant_hora'),
        ),
        migrations.AddIndex(
            model_name='localatendimento',
            index=models.Index(fields=['tenant', 'ativo'], name='transporte__tenant__235994_idx'),
        ),
        migrations.AddConstraint(
            model_name='localatendimento',
            constraint=models.UniqueConstraint(fields=('tenant', 'cidade_destino', 'nome'), name='uq_local_atend_tenant_cidade_nome'),
        ),
        migrations.AddIndex(
            model_name='localembarque',
            index=models.Index(fields=['tenant', 'ativo'], name='transporte__tenant__8d9311_idx'),
        ),
        migrations.AddConstraint(
            model_name='localembarque',
            constraint=models.UniqueConstraint(fields=('tenant', 'nome'), name='uq_local_emb_tenant_nome'),
        ),
        migrations.AddIndex(
            model_name='motorista',
            index=models.Index(fields=['tenant', 'ativo'], name='transporte__tenant__d7c9b3_idx'),
        ),
        migrations.AddIndex(
            model_name='motorista',
            index=models.Index(fields=['cnh_validade'], name='transporte__cnh_val_fe9dd3_idx'),
        ),
        migrations.AddConstraint(
            model_name='motorista',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf', ''), _negated=True), fields=('tenant', 'cpf'), name='uq_motorista_tenant_cpf'),
        ),
        migrations.AddConstraint(
            model_name='motorista',
            constraint=models.UniqueConstraint(fields=('tenant', 'cnh'), name='uq_motorista_tenant_cnh'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['tenant', 'nome'], name='transporte__tenant__b82580_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['tenant', 'ativo'], name='transporte__tenant__14636c_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['tenant', 'unidade'], name='transporte__tenant__31c169_idx'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(condition=models.Q(('cpf', ''), _negated=True), fields=('tenant', 'cpf'), name='uq_paciente_tenant_cpf'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(condition=models.Q(('cns', ''), _negated=True), fields=('tenant', 'cns'), name='uq_paciente_tenant_cns'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(condition=models.Q(('cds_individual', ''), _negated=True), fields=('tenant', 'cds_individual'), name='uq_paciente_tenant_cds'),
        ),
        migrations.AddIndex(
            model_name='viagemtransporte',
            index=models.Index(fields=['tenant', 'data', 'status'], name='transporte__tenant__1057d3_idx'),
        ),
        migrations.AddIndex(
            model_name='viagemtransporte',
            index=models.Index(fields=['tenant', 'motorista', 'data'], name='transporte__tenant__28a45c_idx'),
        ),
        migrations.AddIndex(
            model_name='viagemtransporte',
            index=models.Index(fields=['tenant', 'veiculo', 'data'], name='transporte__tenant__4636f5_idx'),
        ),
        migrations.AddIndex(
            model_name='protocoloexame',
            index=models.Index(fields=['tenant', 'status'], name='transporte__tenant__611149_idx'),
        ),
        migrations.AddIndex(
            model_name='protocoloexame',
            index=models.Index(fields=['tenant', 'paciente'], name='transporte__tenant__9731f7_idx'),
        ),
        migrations.AddIndex(
            model_name='protocoloexame',
            index=models.Index(fields=['tenant', 'previsao_retirada'], name='transporte__tenant__485368_idx'),
        ),
        migrations.AddIndex(
            model_name='protocoloexame',
            index=models.Index(fields=['viagem_retirada'], name='transporte__viagem__d5e2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='passageiroviagem',
            index=models.Index(fields=['paciente'], name='transporte__pacient_a1f2fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='passageiroviagem',
            constraint=models.UniqueConstraint(fields=('viagem', 'paciente'), name='uq_passageiro_viagem_paciente'),
        ),
    ]
