# Generated by Django 5.2.13 on 2026-04-26 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organizacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('machine_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('agent_version', models.CharField(blank=True, default='', max_length=20)),
                ('agent_updated_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('is_canary', models.BooleanField(default=False, help_text='Recebe builds beta antes do rollout geral.')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tokens', to='organizacoes.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tokens', to='organizacoes.setor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['-last_seen_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(db_index=True, max_length=255)),
                ('agent_version', models.CharField(blank=True, default='', max_length=20)),
                ('hardware', models.JSONField(blank=True, null=True)),
                ('network', models.JSONField(blank=True, null=True)),
                ('system_info', models.JSONField(blank=True, null=True)),
                ('software', models.JSONField(blank=True, null=True)),
                ('peripherals', models.JSONField(blank=True, null=True)),
                ('alerts', models.JSONField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_heartbeats', to='core.tenant')),
                ('agent_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='agentes.agenttoken')),
            ],
            options={
                'verbose_name': 'Heartbeat',
                'verbose_name_plural': 'Heartbeats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemoteCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('running', 'Executando'), ('success', 'Sucesso'), ('failed', 'Falhou'), ('timeout', 'Tempo esgotado')], default='pending', max_length=20)),
                ('output', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_commands', to='agentes.agenttoken')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_commands_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remote_commands', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Comando remoto',
                'verbose_name_plural': 'Comandos remotos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agenttoken',
            index=models.Index(fields=['tenant', 'active'], name='agentes_age_tenant__68a0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttoken',
            index=models.Index(fields=['machine_id'], name='agentes_age_machine_8a794b_idx'),
        ),
        migrations.AddIndex(
            model_name='agentheartbeat',
            index=models.Index(fields=['machine_id'], name='agentes_age_machine_9e2d29_idx'),
        ),
        migrations.AddIndex(
            model_name='agentheartbeat',
            index=models.Index(fields=['created_at'], name='agentes_age_created_f89a14_idx'),
        ),
        migrations.AddIndex(
            model_name='remotecommand',
            index=models.Index(fields=['agent_token', 'status'], name='agentes_rem_agent_t_ee1747_idx'),
        ),
        migrations.AddIndex(
            model_name='remotecommand',
            index=models.Index(fields=['status', 'created_at'], name='agentes_rem_status_9262bf_idx'),
        ),
    ]
