# Generated by Django 5.2.13 on 2026-04-30 21:51

import apps.agentes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(db_index=True, max_length=255)),
                ('image', models.ImageField(upload_to=apps.agentes.models._screenshot_upload_to)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='agentes.agenttoken')),
                ('remote_command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshots', to='agentes.remotecommand')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Screenshot',
                'verbose_name_plural': 'Screenshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_token', 'created_at'], name='agentes_scr_agent_t_a70e98_idx'), models.Index(fields=['machine_id', 'created_at'], name='agentes_scr_machine_088301_idx')],
            },
        ),
    ]
