# Generated by Django 5.2.13 on 2026-05-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0002_screenshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screenshot',
        ),
    ]
