# Generated by Django 5.2.13 on 2026-05-19 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentes', '0003_remove_screenshot'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('is_global', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_policies_criadas', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Política de Sites',
                'verbose_name_plural': 'Políticas de Sites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('block', 'Bloquear'), ('allow', 'Liberar')], default='block', max_length=8)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='agentes.sitepolicy')),
            ],
            options={
                'verbose_name': 'Regra de Site',
                'verbose_name_plural': 'Regras de Sites',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='WorkstationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_rules', models.JSONField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstation_policies', to='agentes.agenttoken')),
                ('site_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workstation_policies', to='agentes.sitepolicy')),
            ],
            options={
                'verbose_name': 'Política da Workstation',
                'verbose_name_plural': 'Políticas de Workstations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_sites_criados', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Site Bloqueado',
                'verbose_name_plural': 'Sites Bloqueados',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'domain'), name='uq_blockedsite_tenant_domain')],
            },
        ),
        migrations.AddIndex(
            model_name='sitepolicy',
            index=models.Index(fields=['tenant', 'is_global'], name='agentes_sit_tenant__9f97ed_idx'),
        ),
        migrations.AddIndex(
            model_name='sitepolicy',
            index=models.Index(fields=['tenant', 'active'], name='agentes_sit_tenant__8744a5_idx'),
        ),
        migrations.AddIndex(
            model_name='siterule',
            index=models.Index(fields=['category'], name='agentes_sit_categor_27d390_idx'),
        ),
        migrations.AddConstraint(
            model_name='siterule',
            constraint=models.UniqueConstraint(fields=('site_policy', 'domain'), name='uq_siterule_policy_domain'),
        ),
        migrations.AddConstraint(
            model_name='workstationpolicy',
            constraint=models.UniqueConstraint(fields=('agent_token', 'site_policy'), name='uq_wpolicy_agent_policy'),
        ),
    ]
