# Generated by Django 5.2.13 on 2026-04-26 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('codigo', models.CharField(blank=True, default='', max_length=4)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('responsavel', models.CharField(blank=True, default='', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('responsavel', models.CharField(blank=True, default='', max_length=100)),
                ('localizacao', models.CharField(blank=True, default='', max_length=150)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setores', to='organizacoes.secretaria')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'db_table': 'setores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddIndex(
            model_name='secretaria',
            index=models.Index(fields=['tenant', 'ativo'], name='organizacoe_tenant__6edddd_idx'),
        ),
        migrations.AddConstraint(
            model_name='secretaria',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uq_secretaria_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='secretaria',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo', ''), _negated=True), fields=('tenant', 'codigo'), name='uq_secretaria_tenant_codigo'),
        ),
        migrations.AddIndex(
            model_name='setor',
            index=models.Index(fields=['tenant', 'secretaria'], name='setores_tenant__b15ce8_idx'),
        ),
    ]
