# Generated by Django 5.2.13 on 2026-05-04 17:53 — split manualmente

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('organizacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('modelo', models.CharField(choices=[('hex_e50ug', 'hEX E50UG'), ('hex_refresh', 'hEX Refresh (RB750Gr3)'), ('hap_ax2', 'hAP ax²'), ('hap_ax3', 'hAP ax³'), ('ccr2004', 'CCR2004'), ('crs', 'CRS (switch)'), ('outro', 'Outro Mikrotik')], default='hex_e50ug', max_length=32)),
                ('serial_number', models.CharField(blank=True, default='', max_length=64)),
                ('mac_address', models.CharField(blank=True, default='', max_length=17)),
                ('routeros_version', models.CharField(blank=True, default='', max_length=32)),
                ('endereco', models.CharField(blank=True, default='', max_length=255)),
                ('wg_pubkey_device', models.CharField(blank=True, default='', max_length=64)),
                ('wg_privkey_device', models.CharField(blank=True, default='', max_length=64)),
                ('wg_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('wg_handshake_at', models.DateTimeField(blank=True, null=True)),
                ('wg_endpoint_host', models.CharField(blank=True, default='', max_length=255)),
                ('wg_endpoint_port', models.PositiveIntegerField(default=51820)),
                ('api_user', models.CharField(default='divsystem', max_length=64)),
                ('api_password', models.CharField(blank=True, default='', max_length=128)),
                ('api_port', models.PositiveIntegerField(default=443)),
                ('api_use_https', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('provisionando', 'Provisionando'), ('aguardando_bootstrap', 'Aguardando bootstrap'), ('online', 'Online'), ('offline', 'Offline'), ('erro', 'Erro'), ('desativado', 'Desativado')], default='provisionando', max_length=24)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mikrotik_equipamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_mikrotik', to='organizacoes.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_mikrotik', to='organizacoes.setor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Equipamento Mikrotik',
                'verbose_name_plural': 'Equipamentos Mikrotik',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rest_get', 'REST GET'), ('rest_post', 'REST POST'), ('rest_put', 'REST PUT'), ('rest_patch', 'REST PATCH'), ('rest_delete', 'REST DELETE'), ('execute', 'Comando RouterOS (execute)')], max_length=16)),
                ('path', models.CharField(help_text='Ex.: /system/identity ou /ip/firewall/filter', max_length=512)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('sucesso', 'Sucesso'), ('erro', 'Erro')], default='pendente', max_length=16)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('erro', models.TextField(blank=True, default='')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('executado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mikrotik_comandos', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='mikrotik.equipamento')),
            ],
            options={
                'verbose_name': 'Comando Mikrotik',
                'verbose_name_plural': 'Comandos Mikrotik',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['tenant', 'status'], name='mikrotik_eq_tenant__cbcb6b_idx'),
        ),
        migrations.AddIndex(
            model_name='equipamento',
            index=models.Index(fields=['tenant', 'ativo'], name='mikrotik_eq_tenant__082b31_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipamento',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='uq_mikrotik_tenant_slug'),
        ),
        migrations.AddConstraint(
            model_name='equipamento',
            constraint=models.UniqueConstraint(condition=models.Q(('wg_ip', None), _negated=True), fields=('wg_ip',), name='uq_mikrotik_wg_ip'),
        ),
        migrations.AddIndex(
            model_name='comando',
            index=models.Index(fields=['tenant', 'equipamento', '-created_at'], name='mikrotik_co_tenant__8b04fb_idx'),
        ),
        migrations.AddIndex(
            model_name='comando',
            index=models.Index(fields=['tenant', 'status'], name='mikrotik_co_tenant__4d4f96_idx'),
        ),
    ]
