# Generated by Django 5.2.13 — adiciona Device, DeviceObservation, RogueAlert

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('organizacoes', '0001_initial'),
        ('mikrotik', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('hostname', models.CharField(blank=True, default='', max_length=120)),
                ('interface', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(choices=[('dhcp', 'DHCP lease'), ('arp', 'ARP table'), ('bridge', 'Bridge host')], max_length=16)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_observations', to='mikrotik.equipamento')),
            ],
            options={
                'verbose_name': 'Observação de dispositivo',
                'verbose_name_plural': 'Observações de dispositivos',
                'ordering': ['-seen_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('tipo', models.CharField(choices=[('computador', 'Computador'), ('notebook', 'Notebook'), ('impressora', 'Impressora'), ('celular', 'Celular'), ('tablet', 'Tablet'), ('tv', 'Smart TV'), ('camera', 'Câmera IP'), ('ap', 'Access Point'), ('voip', 'VoIP / Telefone IP'), ('servidor', 'Servidor'), ('iot', 'IoT / Outro')], default='computador', max_length=16)),
                ('mac_address', models.CharField(max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('hostname', models.CharField(blank=True, default='', max_length=120)),
                ('responsavel', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('bloqueado', 'Bloqueado'), ('desativado', 'Desativado')], default='ativo', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_interface', models.CharField(blank=True, default='', max_length=32)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True, default='')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mikrotik_devices_criados', to=settings.AUTH_USER_MODEL)),
                ('secretaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='organizacoes.secretaria')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='organizacoes.setor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='mikrotik.equipamento')),
            ],
            options={
                'verbose_name': 'Dispositivo de rede',
                'verbose_name_plural': 'Dispositivos de rede',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RogueAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('primeiro_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('primeiro_hostname', models.CharField(blank=True, default='', max_length=120)),
                ('primeiro_interface', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('aceito', 'Aceito (cadastrado como Device)'), ('bloqueado', 'Bloqueado'), ('ignorado', 'Ignorado')], default='novo', max_length=16)),
                ('contagem', models.PositiveIntegerField(default=1)),
                ('primeiro_visto', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, default='')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rogue_alerts', to='mikrotik.equipamento')),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mikrotik_rogues_resolvidos', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Alerta de dispositivo desconhecido',
                'verbose_name_plural': 'Alertas de dispositivos desconhecidos',
                'ordering': ['-ultima_vez'],
            },
        ),
        migrations.AddIndex(
            model_name='deviceobservation',
            index=models.Index(fields=['tenant', 'equipamento', 'mac_address', '-seen_at'], name='mikrotik_de_tenant__bab1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceobservation',
            index=models.Index(fields=['tenant', '-seen_at'], name='mikrotik_de_tenant__ae5bec_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['tenant', 'equipamento', 'status'], name='mikrotik_de_tenant__56f81d_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['tenant', 'mac_address'], name='mikrotik_de_tenant__ff9e97_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('equipamento', 'mac_address'), name='uq_device_eq_mac'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('ip_address', None), _negated=True), fields=('equipamento', 'ip_address'), name='uq_device_eq_ip'),
        ),
        migrations.AddIndex(
            model_name='roguealert',
            index=models.Index(fields=['tenant', 'equipamento', 'status'], name='mikrotik_ro_tenant__bd326b_idx'),
        ),
        migrations.AddConstraint(
            model_name='roguealert',
            constraint=models.UniqueConstraint(fields=('equipamento', 'mac_address'), name='uq_rogue_eq_mac'),
        ),
    ]
