# Generated by Django 5.2.13 on 2026-05-04 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('mikrotik', '0002_devices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('aplicada_em', models.DateTimeField(blank=True, null=True)),
                ('aplicada_erro', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mikrotik_politicas_criadas', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas', to='mikrotik.equipamento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Política de filtro',
                'verbose_name_plural': 'Políticas de filtro',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoliticaAlvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='politicas_aplicadas', to='mikrotik.device')),
                ('politica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alvos', to='mikrotik.politica')),
            ],
            options={
                'verbose_name': 'Alvo de política',
                'verbose_name_plural': 'Alvos de política',
            },
        ),
        migrations.CreateModel(
            name='RegraDominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=255)),
                ('incluir_subdominios', models.BooleanField(default=True, help_text='Se ligado, bloqueia também *.<dominio> (ex.: m.facebook.com).')),
                ('comentario', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('politica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='mikrotik.politica')),
            ],
            options={
                'verbose_name': 'Regra de domínio',
                'verbose_name_plural': 'Regras de domínio',
                'ordering': ['dominio'],
            },
        ),
        migrations.AddIndex(
            model_name='politica',
            index=models.Index(fields=['tenant', 'equipamento', 'ativo'], name='mikrotik_po_tenant__556f2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='politica',
            constraint=models.UniqueConstraint(fields=('equipamento', 'nome'), name='uq_politica_eq_nome'),
        ),
        migrations.AddConstraint(
            model_name='politicaalvo',
            constraint=models.UniqueConstraint(fields=('politica', 'device'), name='uq_politicaalvo_politica_device'),
        ),
        migrations.AddConstraint(
            model_name='regradominio',
            constraint=models.UniqueConstraint(fields=('politica', 'dominio'), name='uq_regradominio_politica_dominio'),
        ),
    ]
