# Generated by Django 5.2.13 on 2026-05-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0003_politica_politicaalvo_regradominio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politica',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Aplica em todos os clientes do hEX (DNS sinkhole apenas, sem firewall por src-mac).'),
        ),
        migrations.AddField(
            model_name='regradominio',
            name='categoria',
            field=models.CharField(blank=True, default='', help_text='Slug da categoria curada (redes_sociais, streaming, ...) ou vazio se domínio individual.', max_length=64),
        ),
    ]
