# Generated by Django 5.2.13 on 2026-05-19 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, default='')),
                ('intervalo_dias', models.PositiveIntegerField()),
                ('duracao_estimada_minutos', models.PositiveIntegerField(default=60)),
                ('checklist', models.JSONField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Manutenção',
                'verbose_name_plural': 'Tipos de Manutenção',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('entrada_manha', models.TimeField(blank=True, null=True)),
                ('saida_manha', models.TimeField(blank=True, null=True)),
                ('entrada_tarde', models.TimeField(blank=True, null=True)),
                ('saida_tarde', models.TimeField(blank=True, null=True)),
                ('total_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tipo_atividade', models.CharField(blank=True, default='', max_length=100)),
                ('competencia', models.CharField(max_length=7)),
                ('observacao', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Horas',
                'verbose_name_plural': 'Registros de Horas',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=100)),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('renavam', models.CharField(blank=True, default='', max_length=11)),
                ('chassi', models.CharField(blank=True, default='', max_length=17)),
                ('capacidade_passageiros', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='DiarioBordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida_em', models.DateTimeField()),
                ('retorno_em', models.DateTimeField(blank=True, null=True)),
                ('km_saida', models.PositiveIntegerField()),
                ('km_retorno', models.PositiveIntegerField(blank=True, null=True)),
                ('destino', models.CharField(max_length=255)),
                ('finalidade', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diarios_bordo_autorizador', to=settings.AUTH_USER_MODEL)),
                ('condutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diarios_bordo_condutor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diário de Bordo',
                'verbose_name_plural': 'Diários de Bordo',
                'ordering': ['-saida_em'],
            },
        ),
    ]
