# Generated by Django 5.2.13 on 2026-05-19 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('frota', '0001_initial'),
        ('organizacoes', '0001_initial'),
        ('transporte', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diariobordo',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_bordo', to='transporte.motorista'),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='viagem_transporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_bordo', to='transporte.viagemtransporte'),
        ),
        migrations.AddField(
            model_name='manutencaotipo',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='registrohoras',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_horas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='secretaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculos', to='organizacoes.secretaria'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='diariobordo',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diarios_bordo', to='frota.veiculo'),
        ),
        migrations.AddIndex(
            model_name='veiculo',
            index=models.Index(fields=['tenant', 'secretaria'], name='frota_veicu_tenant__e3904c_idx'),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(fields=('tenant', 'placa'), name='uq_veiculo_tenant_placa'),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('renavam', ''), _negated=True), fields=('tenant', 'renavam'), name='uq_veiculo_tenant_renavam'),
        ),
        migrations.AddConstraint(
            model_name='veiculo',
            constraint=models.UniqueConstraint(condition=models.Q(('chassi', ''), _negated=True), fields=('tenant', 'chassi'), name='uq_veiculo_tenant_chassi'),
        ),
        migrations.AddIndex(
            model_name='diariobordo',
            index=models.Index(fields=['tenant', 'veiculo'], name='frota_diari_tenant__c1c16f_idx'),
        ),
        migrations.AddIndex(
            model_name='diariobordo',
            index=models.Index(fields=['tenant', 'condutor'], name='frota_diari_tenant__b3238d_idx'),
        ),
        migrations.AddIndex(
            model_name='diariobordo',
            index=models.Index(fields=['saida_em'], name='frota_diari_saida_e_9d31dc_idx'),
        ),
        migrations.AddIndex(
            model_name='diariobordo',
            index=models.Index(fields=['motorista'], name='frota_diari_motoris_ab5e2f_idx'),
        ),
        migrations.AddIndex(
            model_name='diariobordo',
            index=models.Index(fields=['viagem_transporte'], name='frota_diari_viagem__2ba0e5_idx'),
        ),
    ]
